/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resource.allocation.system.ViewClasses;

import javax.swing.JOptionPane;
import resource.allocation.system.ControllerClasses.BookingController;
import resource.allocation.system.ControllerClasses.PaymentController;
import resource.allocation.system.ControllerClasses.SpecificDayController;
import resource.allocation.system.ModelClasses.Customer;

/**
 *
 * @author RASHMIKA
 */
public class CustomerOperationUI extends javax.swing.JFrame {

    private Customer customer;

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * Creates new form CustomerOperationUI
     */
    public CustomerOperationUI() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookBt = new javax.swing.JButton();
        editBt = new javax.swing.JButton();
        cancelBt = new javax.swing.JButton();
        logOutBt = new javax.swing.JButton();
        paymentBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resource Allocation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setText("ABC Resource Allocation System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        bookBt.setBackground(new java.awt.Color(51, 102, 255));
        bookBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookBt.setForeground(new java.awt.Color(255, 255, 255));
        bookBt.setText("Book a hall");
        bookBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtActionPerformed(evt);
            }
        });
        getContentPane().add(bookBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        editBt.setBackground(new java.awt.Color(51, 102, 255));
        editBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBt.setForeground(new java.awt.Color(255, 255, 255));
        editBt.setText("Edit booking");
        editBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtActionPerformed(evt);
            }
        });
        getContentPane().add(editBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        cancelBt.setBackground(new java.awt.Color(51, 102, 255));
        cancelBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBt.setForeground(new java.awt.Color(255, 255, 255));
        cancelBt.setText("Cancel booking");
        cancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        logOutBt.setBackground(new java.awt.Color(255, 0, 0));
        logOutBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBt.setForeground(new java.awt.Color(255, 255, 255));
        logOutBt.setText("Log Out");
        logOutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        paymentBt.setBackground(new java.awt.Color(51, 102, 255));
        paymentBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentBt.setForeground(new java.awt.Color(255, 255, 255));
        paymentBt.setText("Payment");
        paymentBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtActionPerformed(evt);
            }
        });
        getContentPane().add(paymentBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 115, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel image 2 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtActionPerformed
        // TODO add your handling code here:
        CustomerLoginUI cfu = new CustomerLoginUI();
        cfu.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutBtActionPerformed

    private void bookBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtActionPerformed
        // TODO add your handling code here:
        HallBookingForm hbf = new HallBookingForm();
        hbf.setVisible(true);
        hbf.setCustomer(customer);
        dispose();
    }//GEN-LAST:event_bookBtActionPerformed

    private void editBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtActionPerformed
        // TODO add your handling code here:
        EditBookingUI ebu = new EditBookingUI();
        ebu.setVisible(true);
        dispose();
    }//GEN-LAST:event_editBtActionPerformed

    private void cancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtActionPerformed
        // TODO add your handling code here:
        try {
            String id = JOptionPane.showInputDialog("Enter Booking ID");

            BookingController bc = new BookingController();
            PaymentController pc = new PaymentController();
            SpecificDayController sdc = new SpecificDayController();
            String type = bc.delete(id);

            if (!type.isEmpty()) {
                sdc.delete(id);
                if(pc.isBookingIdExist(id)){
                    pc.deletePaymentByBookingId(id);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_cancelBtActionPerformed

    private void paymentBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtActionPerformed
        // TODO add your handling code here:
        PaymentUI pu = new PaymentUI();
        pu.setCustomer(customer);
        pu.setVisible(true);
        dispose();
    }//GEN-LAST:event_paymentBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOperationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOperationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOperationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOperationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOperationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBt;
    private javax.swing.JButton cancelBt;
    private javax.swing.JButton editBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logOutBt;
    private javax.swing.JButton paymentBt;
    // End of variables declaration//GEN-END:variables
}
