/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resource.allocation.system.ViewClasses;

import javax.swing.JOptionPane;

/**
 *
 * @author RASHMIKA
 */
public class FirstUI extends javax.swing.JFrame {

    /**
     * Creates new form FirstUI
     */
    public FirstUI() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        compBt = new javax.swing.JButton();
        customerBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resource Allocation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 34)); // NOI18N
        jLabel3.setText("ABC Resource Allocation System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        compBt.setBackground(new java.awt.Color(51, 102, 255));
        compBt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        compBt.setForeground(new java.awt.Color(255, 255, 255));
        compBt.setText("Company");
        compBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compBtActionPerformed(evt);
            }
        });
        getContentPane().add(compBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        customerBt.setBackground(new java.awt.Color(51, 102, 255));
        customerBt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        customerBt.setForeground(new java.awt.Color(255, 255, 255));
        customerBt.setText("Customer");
        customerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtActionPerformed(evt);
            }
        });
        getContentPane().add(customerBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("If you are a customer click on Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        exitBt.setBackground(new java.awt.Color(255, 0, 0));
        exitBt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        exitBt.setText("Exit");
        exitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtActionPerformed(evt);
            }
        });
        getContentPane().add(exitBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 310, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/magnificent-small-banquet-hall-wedding-tips.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Confirm if you want to exit?", "Exit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            dispose();
        }
    }//GEN-LAST:event_exitBtActionPerformed

    private void customerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtActionPerformed
        // TODO add your handling code here:
        CustomerLoginUI cfuObj = new CustomerLoginUI();
        cfuObj.setVisible(true);
        dispose();
    }//GEN-LAST:event_customerBtActionPerformed

    private void compBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compBtActionPerformed
        // TODO add your handling code here:
        AdminLogin afuObj = new AdminLogin();
        afuObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_compBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compBt;
    private javax.swing.JButton customerBt;
    private javax.swing.JButton exitBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
